### ISSUE TITLE
Đổi địa điểm lớp học sang nhà G8 (ĐH Giáo dục)

### ISSUE THREAD

**Issue by truonganhhoang** [truonganhhoang/int3117-2016#130]
Mai chúng ta học ở giảng đường nhà G8 phòng ?01. Mình chưa nghe rõ phòng mà máy đã bị ngắt nên mai các em hỏi lại phòng đào tạo hoặc đến đó tìm/hỏi trực giảng là biết.

**Comment by cuongvumanh** [comment]
học tiết 1-2 phòng 101 thầy ạ :D
