### ISSUE TITLE
Bài tập về nhà tuần 8 (bài tập nhóm)

### ISSUE THREAD

**Issue by truonganhhoang** [truonganhhoang/int3117-2016#151]
Các nhóm chọn và tìm hiểu một trong danh sách một số công cụ, phần mềm hỗ trợ kiểm thử liệt kê ở đây.
https://docs.google.com/spreadsheets/d/1SiKFx2CnjK3H65NIj2AOp77Ezc_PQlHBWZJGULDloy4/edit#gid=1626149913

Các nhóm có thể đề xuất chọn và tìm hiểu công cụ, phần mềm khác, nhưng phải thông qua giáo viên trước.

Buổi học tới ngày 25/10/2016 các nhóm sẽ giới thiệu công cụ trên lớp, và minh họa việc sử dụng các chức năng, tính năng chính của công cụ (chạy) trên một số ví dụ.

**Comment by chinhlv95** [comment]
Thưa thầy, nhóm em chọn Phpunit được không ạ !

**Comment by truonganhhoang** [comment]
các em xem cái http://www.protractortest.org/#/ chưa.. cái này có lẽ phù hợp với nhóm em hơn?

hoặc http://lathonez.github.io/2016/ionic-2-e2e-testing/
