### ISSUE TITLE
Bài tập nhận xét chéo bài tập về nhà của nhau

### ISSUE THREAD

**Issue by truonganhhoang** [truonganhhoang/int3117-2016#192]
Mỗi sv kiểm tra bài của bạn theo thứ tự trong sheet: thứ tự nhận xét... ở link dưới đây:
https://docs.google.com/spreadsheets/d/1SiKFx2CnjK3H65NIj2AOp77Ezc_PQlHBWZJGULDloy4/edit#gid=1918015514
Khi nhận xét xong, lưu vào file: nhanxet-HoTen người được nhận xét.md và cho điểm ở cột trong link trên đồng thời đặt link đến file nhận xét vào cột cuối để bạn tìm cho tiện.

Nội dung nhận xét: mọi khía cạnh của bài tập, từ bài toán, giải quyết, chất lượng mã nguồn, chất lượng bài trình bày (các file readme), chia làm hai phần: phần được, và phần chưa được.

**Comment by kienvtv3** [comment]
@truonganhhoang Em thưa thầy, bài tập của bạn được nhận xét (@dungntm58) có trong repo của bạn đó, nhưng không có trong repo này. Vậy có phải chấm trên repo của bạn đó không, hay chỉ chấm trên repo này ạ?

**Comment by HoangTuyetUET** [comment]
Em thưa thầy, người đầu danh sách chấm cho người cuối danh sách ạ?

**Comment by kienvtv3** [comment]
@HoangTuyetUET Mọi người nhận xét cho người xếp ngay dưới mình trong danh sách của thầy. Người cuối danh sách nhận xét cho người đầu danh sách.

**Comment by truonganhhoang** [comment]
Chấm repo này.. Em báo bạn làm pull requequest lên trc.

**Comment by PhanHai123** [comment]
thưa thầy tại sao em pull requequest cho thầy nhưng thầy ko nhận được bài của em ạ.

**Comment by truonganhhoang** [comment]
Khi bị conflict thì mình ko merge.. Em cập nhật lại repo, rồi tạo
pull request lại xem.

**Comment by phuongnt58** [comment]
Do nhánh của nhóm em pull request bị lỗi bây giờ em mới sửa được và pull request lại. Thầy có thể merge cho nhóm em được không ạ

**Comment by PhanHai123** [comment]
thưa thầy nếu những bạn không có bài tập nhận xét thì  không cần đẩy file nhận xét của mình phải không ạ !

**Comment by truonganhhoang** [comment]
các em vẫn đẩy, và ghi rõ là không có bài của bạn cho rõ ràng nhé.

**Comment by truonganhhoang** [comment]
Bổ sung:
Bổ sung nhận xét cho bạn bằng việc chạy công cụ lint với mã nguồn của người được nhận xét.
Nhận xét lại nếu bạn đề nghị nhận xét lại, sau khi đã chỉnh sửa. Tối đa thêm 2 lần.
