### ISSUE TITLE
Nhận bổ sung trang sách để test

### ISSUE THREAD

**Issue by trieudh58** [truonganhhoang/int3117-2016#24]
Dear all,

Trong buổi học hôm qua, do có chút nhầm lẫn trong khi tính toán số trang; cộng thêm lớp mình chưa đi đủ, nên vẫn còn **hơn 80 ~~trang~~ tờ sách** đang ở chỗ mình.

Vì thế **mỗi người sẽ cần nhận tổng số 04 ~~trang~~ tờ** để hoàn thiện bài tập test tuần này. Bạn nào chưa có, hoặc đang nhận chưa đủ 04 ~~trang~~ tờ thì lên trường gặp mình trong các ngày **T4 (hôm nay), T5, T6 tới.**

SĐT của mình: **0166 77 44 366**. Các bạn có thể hẹn gặp mình để nhận đủ lượng trang sách.
Riêng cả ngày hôm nay (T4) mình sẽ ở phòng lab 312E3 + từ tiết 6-8 học ở 407-A1-ĐHSP.

Nhờ các nhóm trưởng thông báo tin nhắn này đến các thành viên của mình với ạ.
Cảm ơn mọi người đã đọc!

**Comment by trieudh58** [comment]
Thưa thầy @truonganhhoang , thầy thêm 1 số selections vào cột "Sách lớp" trong sheet danh sách lớp được không ạ. Vì một số bạn nhận 2 loại sách, chứ không chỉ 1 loại thôi đâu ạ. (VD: 2 trang sách lớp 10, 2 trang sách lớp 11).

**Comment by trieudh58** [comment]
Dear all,

Mình viết cần thêm comment này vì phát hiện mô tả issue mình tạo viết chưa được rõ ràng. **Mỗi người cần nhận đủ 04 TỜ (TỨC LÀ 08 TRANG SÁCH)** chứ không phải là 04 trang như trong email cũ mà thầy đã forward cho các bạn trước đó.
Rất xin lỗi mọi người vì mình viết chưa thoát ý, có thể khiến các bạn hiểu nhầm.

Ngày mai mình ở trường cả ngày (trừ lúc 13h-15h), tại phòng 312E3. Các bạn có thể lên gặp mình để nhận bổ sung đủ số tờ.
Cảm ơn mọi người đã đọc tin.

Em nhờ thầy @truonganhhoang forward lại email cho các bạn với ạ. Em cảm ơn thầy!

**Comment by truonganhhoang** [comment]
Mình đã gửi email rồi. Các em có email của nhau, có thể báo cho các bạn chưa nhận đc thông tin làm bài tập tuần 2.

**Comment by trieudh58** [comment]
Đã phát hết các trang sách của 3 cuốn sách thầy giao.

**Comment by chungnv58** [comment]
Thưa thầy truonganhhoang, hiện em chưa có trang sách để làm test. vậy em xin hỏi là mai em nhận có còn không ạ? và em gặp thầy ở đâu để lấy được ạ?
