### ISSUE TITLE
Chỉnh sửa thư mục bài tập tuần 1

### ISSUE THREAD

**Issue by truonganhhoang** [truonganhhoang/int3117-2016#25]
Nhiều bạn đặt tên thư mục chưa đúng, cần theo quy tắc: NguyenVanA.
Trong thư mục của từng người, có thư mục BT1.
Trong thư mục BT1 này có thêm file readme.txt mô tả bài tập đã làm.

**Comment by HoangTuyetUET** [comment]
Em thưa thầy em sửa không được em up lại thư mục mới được không ạ?

**Comment by truonganhhoang** [comment]
Em tra git command kỹ chưa mà ko sửa đc, hỏi các bạn xem.
https://www.patrick-wied.at/blog/rename-files-and-folders-with-git

**Comment by HoangTuyetUET** [comment]
Em sửa được rồi ạ. Em cám ơn thầy :)
