### ISSUE TITLE
Bài tập tuần 2 - Kiểm thử Sách Mềm

### ISSUE THREAD

**Issue by truonganhhoang** [truonganhhoang/int3117-2016#27]
Hướng dẫn làm bài tập này có ở trong link bên dưới đây.

https://docs.google.com/spreadsheets/d/1UMBUQ4h0fHztrWqXgRFz3l3FyH_9dqlrpsasgomseI0/edit?usp=sharing

Từng sinh viên sử dụng các ô trống của hàng tương ứng để điền các lỗi vào.. có thể xuống dòng trong ô bằng ALT + ENTER.. và kéo ô rộng ra nếu thấy cần thiết.

Có thắc mắc gì các bạn comment tiếp vào issue này.

**Comment by trieudh58** [comment]
Thưa thầy, em đã dùng thử 2 key nhận sách nhưng chỉ nhận được sách từ lớp 1 đến lớp 9 ạ?

**Comment by HoangTuyetUET** [comment]
Anh vào sheet TA10_1_SHS ... ở file hướng dẫn có link từng trang sách 10,11,12 .

**Comment by truonganhhoang** [comment]
Có một số mã sách không thấy sách 10-12, các bạn sẽ được tự động add sách 10-12 vào sau dựa trên email của các bạn. Nên nếu bạn nào đăng ký với Sách Mềm bằng email khác thì cần điền thêm vào cột cuối ở trang danh sách lớp này:
https://docs.google.com/spreadsheets/d/1SiKFx2CnjK3H65NIj2AOp77Ezc_PQlHBWZJGULDloy4/edit#gid=554403396

**Comment by trieudh58** [comment]
Cảm ơn @HoangTuyetUET , anh đã thấy chỗ em chỉ, có điều là trang đáp án dành cho giáo viên anh vẫn chưa tìm thấy đâu. Em có thể chỉ giúp anh không? Cảm ơn em.

**Comment by HoangTuyetUET** [comment]
Mã sách thầy gửi là sách dành cho học sinh anh à.

**Comment by HoangTuyetUET** [comment]
Em thưa thầy sao nhập mã sách vào là sách học sinh không phải sách giáo viên ?

**Comment by truonganhhoang** [comment]
Sách giáo viên với học sinh cũng giống nhau. Giáo viên có thêm chức năng
SHOW KEYS/KEY và một vài điểm nhỏ khác.

Nếu có vấn đề gì, các em gửi email trực tiếp cho anh Học hỗ trợ:
thaihoc.vnu@gmail.com, hocnt@saokhuee.com.

**Comment by NguyenThaiHoc** [comment]
Mình đã sửa lại mã sách cho các bạn.
Các bạn nhập mã bình thường sẽ thấy sách 10, 11, 12.

**Comment by HongDiem** [comment]
Cần kiểm tra cả màu sắc phải không ạ?

**Comment by truonganhhoang** [comment]
Ừ, nghiêng, đậm, màu..
