### ISSUE TITLE
Tài liệu kiểm thử

### ISSUE THREAD

**Issue by truonganhhoang** [truonganhhoang/int3117-2016#278]
Các nhóm nghiên cứu các phụ lục của chuẩn ISO/IEC/IEEE 29119 phần 3 (link dưới), để giới thiệu trình bày trên lớp. Tốt nhất là áp dụng, dựa trên mẫu, ví dụ để tạo ra các 1 tài liệu tương ứng cho một dự án nào đó, để giới thiệu qua ví dụ.

https://www.dropbox.com/s/d0c7rmqaky62h4l/ISO_IEC_IEEE_29119_Part3.pdf?dl=0

Phân công

Nhóm	| Phụ lục
---|---
BigBird	| A
Cloud9	| B
nhóm xyz	| C,D
Nhóm 1	| E,F
Nhóm 3	| G,H
Nhóm 4	| I,J
Nhom 5	| K,L
Nhóm 6	| M,N
Nhóm 7	| O,P
Nhóm 8	| Q,R
Nhóm 9	| S,T
Nhóm 10	| Kiểm tra hoàn thiện phụ lục A-F
Nhóm 11	| Kiểm tra hoàn thiện phụ lục G-N
Nhom 12	| Kiểm tra hoàn thiện phụ lục O-T

**Comment by truonganhhoang** [comment]
Các nhóm hoàn thành và cập nhật tài liệu kiểm thử vào wiki của repo này.
https://github.com/truonganhhoang/int3117-2016/wiki/T%C3%A0i-li%E1%BB%87u-ki%E1%BB%83m-th%E1%BB%AD. 

Mỗi nhóm tìm trong tài liệu (cả phần nội dung chính, không chỉ phần phụ lục) 10 thuật ngữ đưa thêm vào sheet Thuật ngữ ở đây, chú ý dịch các thuật ngữ sang tiếng Việt luôn.
https://docs.google.com/spreadsheets/d/1SiKFx2CnjK3H65NIj2AOp77Ezc_PQlHBWZJGULDloy4/edit#gid=596848214

Hạn cuối là ngày 3/12/2016.

**Comment by trieudh58** [comment]
@truonganhhoang thưa thầy, thầy cấp quyền ghi để em có thể edit wiki với ạ. Wiki không pull request được ạ.
Thêm nữa là sheet để điền thuật ngữ thầy đang để cho phép comment thôi ạ, và các cột trong sheet cũng chưa ghi rõ nội dung từng cột là gì.
Sheet này cũng đang được để trong file của lớp **Các vấn đề hiện đại của CNTT**, không biết thầy có để nhầm chỗ không ạ?

**Comment by truonganhhoang** [comment]
mình đã cập nhật lại rồi. tài liệu các bạn đưa qua .md ở trong repo nhóm cũng đc rồi.
