### ISSUE TITLE
tunn58 sửa lại readme ở thư mục gốc

### ISSUE THREAD

**Issue by truonganhhoang** [truonganhhoang/int3117-2016#39]
em ghi đè lên file readme chung của cả lớp rồi, em revert lại readme bản cũ.

**Comment by tunn58** [comment]
Em đã thử revert lại bản cũ nhưng gặp lỗi "unable to revert commit", em đã sửa lại file như cũ và tạo request pull.
Em xin lỗi thầy.

**Comment by truonganhhoang** [comment]
ok
