### ISSUE TITLE
Bài tập về nhà tuần 3

### ISSUE THREAD

**Issue by truonganhhoang** [truonganhhoang/int3117-2016#40]
Nâng cấp bài tập tuần 1 bằng cách áp dụng một kỹ thuật mà em thấy phù hợp nhất. Chú ý đến phương pháp chi tiết, ví dụ Kiểm thử biên **mạnh** chứ không chung chung là Kiểm thử biên. Giải thích tại sao kỹ thuật em lựa chọn là phù hợp nhất.

Sản phẩm phải nộp:
- File readme.md giải thích tại sao phù hợp và trình bày việc áp dụng kỹ thuật để tạo ra các ca kiểm thử.
- Thay các ca kiểm thử cũ bằng các ca kiểm thử mới tạo ra ở trên. Thực hiện (chạy) kiểm thử lại và sửa lỗi chương trình nếu có. 
- Bổ sung báo cáo vào readme.md về kết quả việc áp dụng kỹ thuật kiểm thử phù hợp, đã mang lại kết quả gì tốt hơn ko.

**Comment by trieudh58** [comment]
Thưa thầy, bài tập này thì làm riêng ra thư mục BT2 hay update vào thư mục cũ BT1 ạ?

**Comment by truonganhhoang** [comment]
Mình nghĩ để thư mục cũ, BT1, vì đã có lịch sử trước của nó rồi.

**Comment by trieudh58** [comment]
Ở thư mục BT1 đã có sẵn một file README.md rồi, bây giờ thêm 1 file khác là readme.md được không ạ?

**Comment by truonganhhoang** [comment]
ko, các em bổ sung, cập nhật vào file đó.

**Comment by dungnd58** [comment]
Thưa thầy, bọn em làm trên nhánh fork xong gửi pull request. Hay push trực tiếp vào thư mục nhóm trên nhánh master luôn ạ ?

**Comment by truonganhhoang** [comment]
Em push trực tiếp luôn đc.

**Comment by dungnd58** [comment]
Hình như phải có permission mới push được lên nhánh chính ạ ?

**Comment by truonganhhoang** [comment]
À, cái này các em tạo pull request thôi.

**Comment by duckm8795** [comment]
Em thưa thầy , bây giờ em muốn bỏ code ở phần 1 đi để thay bằng code mới có được ko thầy, vì code phần 1 đơn giản quá , nên bây giờ test cũng khó .

**Comment by PhanHai123** [comment]
thưa thầy cả mô tả , giải thích tại sao phù hợp và trình bày việc áp dụng kỹ thuật để tạo ra các ca kiểm thử cũng để vào thư mục cũ luôn ạ

**Comment by truonganhhoang** [comment]
Nhiều bạn làm chất lượng chưa tốt, các bạn chữa theo một số lỗi mình chỉ ra trong buổi code review sáng nay. Sẽ có phần chấm điểm ở phần chất lượng bên trong của bài tập này.
